# Generated by Django 5.2.1 on 2026-07-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostViewedProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Топ переглядів',
                'verbose_name_plural': 'Топ переглядів',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='NewArrivalProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Новинка',
                'verbose_name_plural': 'Новинки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='TopSaleProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Топ продажу',
                'verbose_name_plural': 'Топ продажу',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
    ]
