# Generated by Django 5.2.1 on 2026-07-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_onsaleproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва у фільтрі')),
                ('filter_type', models.CharField(choices=[('brand', 'Бренд'), ('price', 'Ціна'), ('category', 'Вид (категорії)'), ('in_stock', 'Наявність'), ('attribute', 'Характеристика товару')], max_length=20, verbose_name='Тип')),
                ('attribute_name', models.CharField(blank=True, help_text='Для типу «Характеристика» — має збігатися з назвою атрибута товару (напр. Колір).', max_length=120, verbose_name='Назва характеристики')),
                ('fallback_values', models.TextField(blank=True, help_text='По одному значенню в рядку. Показуються, якщо в товарах ще немає таких атрибутів.', verbose_name='Значення за замовчуванням')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('open_by_default', models.BooleanField(default=False, verbose_name='Розгорнутий за замовчуванням')),
            ],
            options={
                'verbose_name': 'Фільтр каталогу',
                'verbose_name_plural': 'Фільтри каталогу',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#2453E0', help_text='HEX, наприклад #2453E0', max_length=7, verbose_name='Колір категорії'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_file',
            field=models.FileField(blank=True, help_text='SVG, PNG або JPG. Якщо завантажено — має пріоритет над пресетом.', upload_to='categories/icons/', verbose_name='Власна іконка (файл)'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_key',
            field=models.CharField(blank=True, choices=[('home', 'Дім'), ('suitcase', 'Валіза'), ('chair', 'Крісло'), ('tools', 'Інструменти'), ('kids', 'Дитячі'), ('sport', 'Спорт'), ('tractor', 'Трактор'), ('pet', 'Зоо'), ('sale', 'Уцінка'), ('garage', 'СТО / авто'), ('grid', 'Сітка / загальна'), ('star', 'Зірка')], default='grid', max_length=30, verbose_name='Іконка (пресет)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Іконка (CSS class, застаріле)'),
        ),
    ]
