# Generated by Django 5.2.1 on 2026-07-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_seed_catalog_filters_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='Слаг (URL)'),
        ),
        migrations.AlterField(
            model_name='catalogfilter',
            name='attribute_name',
            field=models.CharField(blank=True, help_text='Для типу «Характеристика товару» вкажіть точну назву атрибута (наприклад: Колір).', max_length=120, verbose_name='Назва характеристики'),
        ),
        migrations.AlterField(
            model_name='catalogfilter',
            name='fallback_values',
            field=models.TextField(blank=True, help_text='Кожне значення з нового рядка. Показуються, якщо в товарів ще немає таких атрибутів.', verbose_name='Значення за замовчуванням'),
        ),
        migrations.AlterField(
            model_name='catalogfilter',
            name='filter_type',
            field=models.CharField(choices=[('brand', 'Бренд'), ('price', 'Ціна'), ('category', 'Вид (категорії)'), ('in_stock', 'Наявність'), ('attribute', 'Характеристика товару')], max_length=20, verbose_name='Тип фільтра'),
        ),
        migrations.AlterField(
            model_name='catalogfilter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='catalogfilter',
            name='open_by_default',
            field=models.BooleanField(default=False, verbose_name='Розгорнути за замовчуванням'),
        ),
        migrations.AlterField(
            model_name='catalogfilter',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок показу'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#2453E0', help_text='Оберіть колір у форматі HEX, наприклад #2453E0.', max_length=7, verbose_name='Колір категорії'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Іконка (CSS-клас, застаріле)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_file',
            field=models.FileField(blank=True, help_text='Завантажте SVG, PNG або JPG. Якщо файл є — він замінює іконку зі списку.', upload_to='categories/icons/', verbose_name='Власна іконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_key',
            field=models.CharField(blank=True, choices=[('home', 'Дім'), ('suitcase', 'Валіза'), ('chair', 'Крісло'), ('tools', 'Інструменти'), ('kids', 'Дитячі товари'), ('sport', 'Спорт'), ('tractor', 'Трактор'), ('pet', 'Зоотовари'), ('sale', 'Уцінка'), ('garage', 'СТО / авто'), ('grid', 'Загальна (сітка)'), ('star', 'Зірка')], default='grid', help_text='Одна з 12 готових іконок для категорії.', max_length=30, verbose_name='Іконка зі списку'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='SEO-опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='Слаг (URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='SEO-опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=320, unique=True, verbose_name='Слаг (URL)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt-текст'),
        ),
    ]
