# Generated by Django 5.2.1 on 2026-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productimage_path_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Стабільний id з YML (category id). Потрібен для коректної ієрархії.', max_length=32, verbose_name='ID у вигрузці Siker'),
        ),
    ]
