# Generated by Django 5.2.1 on 2026-06-26 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('content', models.TextField(verbose_name='Контент')),
                ('image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Зображення')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Блог',
                'ordering': ['-published_at'],
            },
        ),
    ]
