# Generated by Django 5.2.1 on 2026-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropshippingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Імʼя')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=120, verbose_name='Місто')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('processing', 'В обробці'), ('done', 'Завершена')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка дропшипінг',
                'verbose_name_plural': 'Заявки дропшипінг',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('discount_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Підписка',
                'verbose_name_plural': 'Підписки',
            },
        ),
        migrations.CreateModel(
            name='ProductInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Назва')),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='Артикул')),
                ('file', models.FileField(blank=True, upload_to='instructions/', verbose_name='PDF')),
                ('external_url', models.URLField(blank=True, verbose_name='Посилання')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Інструкція',
                'verbose_name_plural': 'Інструкції',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Контент')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Інфо-сторінка',
                'verbose_name_plural': 'Інфо-сторінки',
            },
        ),
    ]
