# Generated by Django 5.2.1 on 2026-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_email',
            field=models.BooleanField(default=False, help_text='Лише для staff/адмінів. На адресу облікового запису.', verbose_name='Отримувати email-сповіщення про замовлення'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_messenger',
            field=models.BooleanField(default=False, help_text='Лише для staff/адмінів. На номер з поля «Телефон».', verbose_name='Отримувати сповіщення в месенджер (Viber/SMS)'),
        ),
    ]
