# Generated by Django 5.2.1 on 2026-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('discount_type', models.CharField(choices=[('percent', 'Відсоток'), ('fixed', 'Фіксована сума')], max_length=10, verbose_name='Тип')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Дійсний з')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Дійсний до')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. використань')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Використано')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
            },
        ),
    ]
