# Generated by Django 5.2.1 on 2026-06-26 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер')),
                ('first_name', models.CharField(max_length=100, verbose_name='Імʼя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('delivery_service', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта')], max_length=20, verbose_name='Доставка')),
                ('delivery_city', models.CharField(max_length=150, verbose_name='Місто')),
                ('delivery_type', models.CharField(blank=True, choices=[('warehouse', 'Відділення'), ('postomat', 'Поштомат'), ('courier', "Кур'єр")], max_length=20, verbose_name='Тип НП')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адреса / відділення')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума товарів')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доставка')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Разом')),
                ('promo_code', models.CharField(blank=True, max_length=50, verbose_name='Промокод')),
                ('status', models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('liqpay_order_id', models.CharField(blank=True, max_length=64, verbose_name='LiqPay order ID')),
                ('liqpay_transaction_id', models.CharField(blank=True, max_length=64, verbose_name='LiqPay transaction')),
                ('tracking_number', models.CharField(blank=True, max_length=64, verbose_name='ТТН')),
                ('idempotency_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('create_account', models.BooleanField(default=False, verbose_name='Створити акаунт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_sku', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
    ]
