# Generated by Django 5.2.1 on 2026-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('liqpay', 'Онлайн оплата (LiqPay)'), ('cod', 'Оплата при отриманні (накладений платіж)'), ('bank_transfer', 'Безготівковий розрахунок (на рахунок)')], default='liqpay', max_length=20, verbose_name='Спосіб оплати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Нове'), ('awaiting_payment', 'Очікує оплату'), ('paid', 'Оплачено'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('done', 'Виконано'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
