# Generated by Django 5.2.1 on 2026-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Oyra', max_length=100, verbose_name='Назва сайту')),
                ('phone', models.CharField(default='+38 (000) 000-00-00', max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@oyra.ua', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='м. Львів, Україна', max_length=255, verbose_name='Адреса')),
                ('work_hours', models.CharField(default='Пн–Пт: 9:00–18:00', max_length=255, verbose_name='Години роботи')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('newsletter_discount', models.PositiveSmallIntegerField(default=15, verbose_name='Знижка за підписку %')),
                ('free_delivery_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Безкоштовна доставка від')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description головної')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
