# Generated by Django 5.2.1 on 2026-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_details_note',
            field=models.TextField(blank=True, help_text='Текст, який побачить клієнт при виборі безготівкового розрахунку.', verbose_name='Додаткова інструкція до оплати'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_edrpou',
            field=models.CharField(blank=True, max_length=20, verbose_name='ЄДРПОУ / ІПН'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_recipient',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отримувач (ФОП/ТОВ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_emails',
            field=models.TextField(blank=True, help_text='Одна або кілька адрес через кому чи з нового рядка.', verbose_name='Email для сповіщень про замовлення'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_phones',
            field=models.TextField(blank=True, help_text='Номери для дублюючих сповіщень. Через кому або з нового рядка.', verbose_name='Телефони для Viber/SMS (TurboSMS)'),
        ),
    ]
